export {default as Navbar} from "./Navbar"
export {default as Home} from "./Home"
export {default as Education} from "./Education"
export {default as Skills} from "./Skills"
export {default as Projects} from "./Projects"
export {default as Certificates} from "./Certificates"
export {default as Contact} from "./Contact"
export {default as Footer} from "./Footer"